# .streamlit/config.toml

[browser]
gatherUsageStats = false

[server]
fileWatcherType = "none"    # avoid inotify errors in Spaces
headless = true
runOnSave = false
enableXsrfProtection = true
maxUploadSize = 200
