# FastAPI backend configuration
BACKEND_URL = "https://dhf-backend-xxxxx-uc.a.run.app"
BACKEND_TOKEN = "change-me"

# Google Drive integration (Service Account JSON as single-line triple-quoted string)
SERVICE_ACCOUNT_JSON = """{
  "type": "service_account",
  "project_id": "your-project-id",
  "private_key_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqh...\n-----END PRIVATE KEY-----\n",
  "client_email": "service-account@your-project-id.iam.gserviceaccount.com",
  "client_id": "123456789012345678901",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/service-account%40your-project-id.iam.gserviceaccount.com"
}"""

# Drive folder to store outputs (must be shared with Service Account)
DRIVE_FOLDER_ID = "19udmXqrKypQ7uVRPK5Mdmzo5BNOlG_KQ"

# Local outputs directory inside Spaces (persisted in /data)
OUTPUT_DIR = "/data/streamlit_outputs"
